export const LEDGER_ACCOUNT_CODES = {
  // Assets
  CASH: '1000',
  LOANS_RECEIVABLE: '1100',

  // Liabilities
  CUSTOMER_DEPOSITS: '2000',
  UNAPPLIED_RECEIPTS: '2050',
  UNAPPLIED_DISBURSEMENTS: '2100',

  // Income
  FEE_COMMISSION_INCOME: '4100',
  SUBSCRIPTION_FEE_INCOME: '4200',

  // Expense
  LOAN_REPAYMENT_EXPENSE: '5100',
  COMMISSION_EXPENSE: '5200',
  SUBSCRIPTION_FEE_EXPENSE: '5300',
} as const;
